apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA1
          artifact-id: 57e2fc11-8a6d-4206-883d-435b1d684154
          target-environment: ProdEnv