apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA2
          artifact-id: 2cdc7ee4-0c5f-4344-8607-ca3e039dc1b0
          target-environment: ProdEnv