apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CP Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA2
          artifact-id: 513d234a-c6aa-48c6-9cf2-cfc822154fa2
          target-environment: ProdEnv